using UnityEngine;

namespace Oculus.Interaction
{
    /// <summary>
    /// Used on a SerializedField surfaces the expectation that this field can remain empty.
    /// </summary>
    public class OptionalAttribute : PropertyAttribute
    {
        [System.Flags]
        public enum Flag
        {
            /// <summary>
            /// Presents the Optional tag and moves it into the Optional Section
            /// </summary>
            None = 0,
            /// <summary>
            /// Indicates that if the reference is missing, a new object will be
            /// created and linked to it during runtime.
            /// </summary>
            AutoGenerated = 1 << 0,
            /// <summary>
            /// Indicates that even though the reference is Optional, it is important
            /// for the component to work as expected.
            /// </summary>
            DontHide = 1 << 1
        }

        public Flag Flags { get; private set; } = Flag.None;

        public OptionalAttribute() { }

        public OptionalAttribute(Flag flags)
        {
            Flags = flags;
        }
    }
}
